services:
  app:
    build: .
    ports:
      - "${DOCKER_APP_PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "${DOCKER_DB_PORT}:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
